name: ecom
description: "A high-traffic e-commerce application."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # UI & Design
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  infinite_scroll_pagination: ^4.0.0
  flutter_rating_bar: ^4.0.1

  # Utils
  intl: ^0.20.2
  logger: ^2.0.2+1

  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  retrofit_generator: ^10.0.6
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #     - asset: assets/fonts/Poppins-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Poppins-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Poppins-Bold.ttf
  #       weight: 700
